# Permalinks
permalink: "/:categories/:title/"

# Setup
title: Dan Kim
tagline: "@dankimio"
description: A blog about software development, productivity, design and travel by Dan Kim.
url: "https://dankim.io"
paginate: 10
baseurl: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Dan Kim
  url: "https://twitter.com/dankimio"
  email: "itsdanya@gmail.com"
  twitter: dankimio
  instagram: dankimio
  github: dankimio

# Custom vars
version: 2.0.0
analytics_id: UA-76222042-1

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
